Content: Add Hacktoberfest 2020 blog post
mumble-voip/mumble-www pull request #110
Opened 2020-10-01 21:18 UTC by Kissaki

* Intro to Hacktoberfest
* Mention our ticket labels
* Mention that we welcome contributions in general

2020-10-01 22:28 UTC, davidebeatrici requested changes

2020-10-01 22:28 UTC, davidebeatrici commented on hugo/content/blog/2020-10-01-hacktoberfest.md
> +We marked our issue tickets that are [marked with the good first issue](https://github.com/mumble-voip/mumble/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) with the [Hacktoberfest lab
```suggestion
We marked our issue tickets that are [marked with the **good first issue** label](https://github.com/mumble-voip/mumble/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) with the [**Hacktoberfest** label](https://github.com/mumble-voip/mumble/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest) as well. These could be a good starting point for new contributors.
```

2020-10-01 22:28 UTC, davidebeatrici commented on hugo/content/blog/2020-10-01-hacktoberfest.md
> +The [help wanted label](https://github.com/mumble-voip/mumble/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) also contains tickets for which we would welcome contributions. These may be mor
```suggestion
The [**help wanted** label](https://github.com/mumble-voip/mumble/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) also contains tickets for which we would welcome contributions. These may be more difficult or more effort though.
```

2020-10-02 01:41 UTC, davidebeatrici approved these changes

2020-10-02 05:37 UTC, Krzmbrzl approved these changes

2020-10-02 05:37 UTC, Krzmbrzl commented on hugo/content/blog/2020-10-01-hacktoberfest.md
> +This post is meant as a shoutout to this event, but also to lay out how we intend to handle it and pointers how you can start contributing to our project.
```suggestion
This post is meant as a shoutout to this event, but also to lay out how we intend to handle it and to point out how you can start contributing to our project.
```

2020-10-02 16:30 UTC, merged